# Generated by Django 3.1 on 2020-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mup_back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='boletim',
            name='text',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='general',
            name='text',
            field=models.CharField(max_length=10000000),
        ),
    ]
